// Generated by CoffeeScript 1.6.2
(function() {
  var bcrypt;

  bcrypt = require('bcrypt');

  exports.encrypt = function(password, callback) {
    return bcrypt.genSalt(10, function(err, salt) {
      if (err) {
        return callback(err);
      } else {
        return bcrypt.hash(password, salt, function(err, hash) {
          return callback(err, hash);
        });
      }
    });
  };

  exports.compare = function(password, userPassword, callback) {
    return bcrypt.compare(password, userPassword, function(err, isPasswordMatch) {
      if (err) {
        return callback(err);
      } else {
        return callback(null, isPasswordMatch);
      }
    });
  };

}).call(this);
