// Generated by CoffeeScript 1.6.2
(function() {
  var Schema, accounts, mongoose, users;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  users = new Schema({
    name: String,
    company: String,
    email: {
      type: String,
      required: true,
      unique: true
    },
    password: {
      type: String,
      required: true
    },
    accountID: String
  });

  accounts = new Schema({
    name: String,
    company: String,
    email: {
      type: String,
      required: true
    },
    password: {
      type: String,
      required: true
    },
    devices: Array,
    users: [users]
  });

  accounts.pre('save', function(next) {
    this.users.push({
      name: this.name,
      company: this.company,
      email: this.email,
      password: this.password,
      accountID: this._id
    });
    return next();
  });

  mongoose.model('Account', accounts);

}).call(this);
