// Generated by CoffeeScript 1.6.2
(function() {
  var Schema, mongoose, users;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  users = new Schema({
    name: String
  });

  users.pre('save', function(next) {
    return next();
  });

  mongoose.model('User', users);

}).call(this);
