// Generated by CoffeeScript 1.6.2
(function() {
  var app, auth, express, port, server, snowshoestamp;

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.cookieParser());
    app.use(express.methodOverride());
    return app.use(app.router);
  });

  snowshoestamp = require('./snowshoestamp');

  auth = new snowshoestamp('0ce618911082c8862495', '02cdd95d9c917cf66dd73f7d9ed2208d56e1845a');

  app.all('/snowshoecallback', function(req, res) {
    return auth.validateStamp(req.body);
  });

  app.get('/stampscreen', function(req, res) {
    return auth.stampScreen(req, res);
  });

  port = process.env.PORT || 3000;

  server.listen(port, function() {
    return console.log("Server running on port " + port);
  });

}).call(this);
