// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app, passport) {
    var account, auth, index, users;

    index = require('./controllers/index');
    app.get('/', app.ensureAuthenticated, function() {});
    account = require('./controllers/account');
    app.get('/account', app.ensureAuthenticated, function() {});
    auth = require('./controllers/auth');
    app.get('/login', auth.login);
    app.get('/logout', auth.logout);
    app.post('/auth', passport.authenticate('local', {
      failureRedirect: '/login'
    }), auth.auth);
    app.get('/auth/facebook', passport.authenticate('facebook'), function(req, res) {});
    app.get('/auth/facebook/callback', passport.authenticate('facebook', {
      failureRedirect: '/login'
    }), auth.fbCallback);
    users = require('./controllers/users');
    return app.post('/createaccount', app.ensureAuthenticated, users.createAccount);
  };

}).call(this);
