// Generated by CoffeeScript 1.8.0
(function() {
  var SnowShoeStamp, queryString, request;

  request = require('request');

  queryString = require('query-string');

  module.exports = SnowShoeStamp = (function() {
    function SnowShoeStamp(apiKey, apiSecret) {
      this.apiKey = apiKey;
      this.apiSecret = apiSecret;
      this.baseURI = 'https://beta.snowshoestamp.com/api/v2';
    }

    SnowShoeStamp.prototype.stampScreen = function(req, res, queryParams) {
      var query;
      query = queryString.stringify(queryParams);
      return res.redirect(("http://beta.snowshoestamp.com/applications/client/" + this.apiKey + "?") + query);
    };

    SnowShoeStamp.prototype.validateStamp = function(data, cb) {
      var oauth, url;
      cb = cb != null ? cb : function() {};
      oauth = {
        consumer_key: this.apiKey,
        consumer_secret: this.apiSecret
      };
      url = "" + this.baseURI + "/stamp";
      return request.post({
        url: url,
        oauth: oauth,
        form: data
      }, function(e, r, body) {
        return cb(body);
      });
    };

    return SnowShoeStamp;

  })();

}).call(this);
