// Generated by CoffeeScript 1.6.2
(function() {
  var Account, LocalStrategy, mongoose, passwords;

  mongoose = require('mongoose');

  Account = mongoose.model('Account');

  passwords = require('../modules/passwords');

  LocalStrategy = require('passport-local').Strategy;

  module.exports = function(passport, config) {
    var _this = this;

    passport.serializeUser(function(user, done) {
      return done(null, user);
    });
    passport.deserializeUser(function(obj, done) {
      return done(null, obj);
    });
    return passport.use(new LocalStrategy(function(email, pass, done) {
      return Account.findOne({
        'users.email': email
      }, {
        'users.$': 1
      }, function(error, account) {
        var _this = this;

        if (!error && account) {
          return passwords.compare(pass, account.users[0].password, function(err, isMatch) {
            if (err) {
              done(err);
            }
            if (!isMatch) {
              done(null, false, {
                message: 'Incorrect e-mail / password combination.'
              });
            }
            return done(null, account.users[0]);
          });
        } else {
          return done();
        }
      });
    }));
  };

}).call(this);
